# Generated by Django 2.2.5 on 2019-09-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_author_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
    ]
