# Generated by Django 2.2.5 on 2019-09-15 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20190915_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='operations.User'),
            preserve_default=False,
        ),
    ]
