# Generated by Django 2.2.5 on 2019-09-15 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
