# Generated by Django 2.2.5 on 2019-09-15 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_auto_20190915_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
