# Generated by Django 2.2.5 on 2019-09-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_auto_20190918_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='adad', max_length=255),
            preserve_default=False,
        ),
    ]
