# Generated by Django 2.2.5 on 2019-09-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='adf', upload_to=''),
            preserve_default=False,
        ),
    ]
