# Generated by Django 2.2.5 on 2019-09-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
