# Generated by Django 2.2.5 on 2019-09-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_auto_20190922_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user_fire_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
